spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DATN_SD;encrypt=true;trustServerCertificate=true
    username: sa
    password: your_password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
